Algoritmo "Media de idade"
// 


Var
nome1,nome2:caractere
idade1,idade2,media:real

Inicio
  escreva("Dados da primeira Pessoa:")
  leia(nome1)
  escreval("")
  
  escreva("Idade:")
  leia(idade1)
  
  escreval("")

  escreva("Dados da segunda Pessoa:")
  leia(nome2)
  
  escreval("")

  escreva("Idade:")
  leia(idade2)
  escreval("")
  media<-(idade1 + idade2)/2
  escreval("A Idade media de ",nome1, " e ", nome2," e de",media:5:1," Anos.")

Fimalgoritmo